#Numpy array creation

In [578]:
import numpy as np

In [579]:
np_array = np.array([1, 2, 3, 4, 5])
np_array.ndim

1

In [580]:
np_arr = np.array(32)
np_arr.ndim

0

In [581]:
a = np.array([])
b = np.array([[]])
c = np.array([[[]]])
d = np.array([[[[]]]])
e = np.array([[], [], []])

In [582]:
a.ndim, b.ndim, c.ndim, d.ndim, e.ndim

(1, 2, 3, 4, 2)

In [583]:
a.shape, b.shape, c.shape, d.shape, e.shape

((0,), (1, 0), (1, 1, 0), (1, 1, 1, 0), (3, 0))

In [584]:
lst = []
for i in range(1, 11, 2): #(start, stop, step), stop value is not included
    lst.append(i)
lst

[1, 3, 5, 7, 9]

In [585]:
np_arr = np.arange(1, 11, 2) #(start, stop, step), stop value is not included
np_arr

array([1, 3, 5, 7, 9])

In [586]:
arr = np.linspace(0, 1, 10) #(start, stop, number of evenly spaced values btn them)
arr #stop value is included

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [587]:
arr1 = np.logspace(1, 5, 5) #logarithmic scale array -> 10^1, 10^2, 10^3, 10^4, 10^5
arr1 #third parameter denotes evenly spaced number of elements in the numpy array

array([1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05])

In [588]:
arr2 = np.logspace(1, 5, 3) #10^1, 10^3, 10^5
arr2

array([1.e+01, 1.e+03, 1.e+05])

In [589]:
arra = np.zeros(5, dtype = np.int64) #array consists of zeros
arra

array([0, 0, 0, 0, 0])

In [590]:
arrb = np.zeros([3, 4])
arrb

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [591]:
arrc = np.zeros([2, 3, 5, 6, 8], dtype = int) #default datatype is float
arrc

array([[[[[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],

         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],

         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],

         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],

         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0

In [592]:
arr = np.ones([4, 5], dtype = int) #array consists of ones
arr

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [593]:
arr = np.full(10, 2) #(number of elements, value)
arr

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [594]:
arr = np.full([4, 3], 7.5)
arr

array([[7.5, 7.5, 7.5],
       [7.5, 7.5, 7.5],
       [7.5, 7.5, 7.5],
       [7.5, 7.5, 7.5]])

In [595]:
arr1 = np.empty([3, 2]) #Uninitializzed array (Cocerned about creating the array, doesn't care about the values)
arr1

array([[4.9e-324, 9.9e-324],
       [1.5e-323, 2.0e-323],
       [2.5e-323, 3.0e-323]])

In [596]:
arr2 = np.empty([4, 3])
arr2[:] = 8.7
arr2

array([[8.7, 8.7, 8.7],
       [8.7, 8.7, 8.7],
       [8.7, 8.7, 8.7],
       [8.7, 8.7, 8.7]])

#Random number generation

In [597]:
arr = np.random.rand(5) #random floats btn 0 and 1
arr

array([0.38789382, 0.79677649, 0.74306351, 0.69113869, 0.68464211])

In [598]:
arr = np.random.rand(3, 4)
arr

array([[0.49329376, 0.01011981, 0.09973939, 0.47415149],
       [0.86848192, 0.56363701, 0.1202763 , 0.87629591],
       [0.773168  , 0.6580259 , 0.04852887, 0.06694307]])

In [599]:
arr = np.random.randn(2, 3) #Standard normal distribution (mean(where most values cluster) = 0, standard deviation(values tightly packed or spread far away from the mean or the central value) = 1)
arr


array([[-0.18235857, -0.42719375, -1.46482205],
       [ 0.7018493 ,  1.72839958,  1.03969339]])

In [600]:
arr = np.random.normal(0, 0.05, 1000000) #(where most values cluster, values tightly packed or spread far away from the mean or the central value, how many data points)
arr

array([-0.03711928,  0.00618175, -0.00368381, ...,  0.03769061,
       -0.06496295,  0.01949301])

In [601]:
arr1 = np.random.randint(1, 100) #(start, stop, number of values (default number of value = 1))
arr1

55

In [602]:
arr2 = np.random.randint(1, 100, size = 5) # 5 random integers between 1 and 100 inclusive
arr2

array([39, 56, 77,  6, 68])

In [603]:
arr3 = np.random.randint(1, 100, size = (2, 3)) # 2 * 3 = 6 random values between 1 and 100 inclusive
arr3

array([[ 3, 88, 66],
       [79, 39, 20]])

#Numpy data type and type casting

In [604]:
arr = np.array([1.5, 2.8, 3.5, 4.2, 5.9], dtype = np.int64)
arr

array([1, 2, 3, 4, 5])

In [605]:
arr.dtype

dtype('int64')

In [606]:
arr = np.array([1, 2.5, 3.14159, True, "Numpy"])
arr.dtype

dtype('<U32')

In [607]:
arr

array(['1', '2.5', '3.14159', 'True', 'Numpy'], dtype='<U32')

In [608]:
arr = np.array([1, 2, 3, 4, 5])
type_casted_array = arr.astype(np.float64)
type_casted_array

array([1., 2., 3., 4., 5.])

In [609]:
arr = type_casted_array.astype(np.int64)
arr

array([1, 2, 3, 4, 5])

In [610]:
arr = np.array([1, 2.67, 3.1415928, True, "Python"])
try:
    type_casted_array = arr.astype(np.int64)
except Exception as e:
    print(e)

invalid literal for int() with base 10: np.str_('2.67')


#Multidimentional Numpy Array

In [611]:
arr = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]]) #multidimentional array must be homogeneous

In [612]:
arr.ndim

2

In [613]:
arr.shape

(3, 3)

In [614]:
arr.size

9

In [615]:
arr.itemsize #each element in numpy array arr is taking 'x' bytes of memory

8

In [616]:
try:
    arr = np.array([[1, 2],
               [3, 4, 5, 6],
               [7, 8, 9]]) #inhomogeneous shape isn't allowed
    arr.ndim
    arr.shape
    arr.size
    arr.itemsize
except Exception as e:
    print(e)

setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.


#Numpy array reshaping

In [617]:
arr = np.array([1, 2, 3, 4, 5, 6])

In [618]:
reshaped_arr1 = arr.reshape(2, 3)
reshaped_arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [619]:
reshaped_arr2 = reshaped_arr1.reshape(3, 2)
reshaped_arr2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [620]:
#ravel converts any numpy array into a 1D array and changes made in the ravel array will also reflect in the original numpy array
reshaped_arr3 = reshaped_arr1.ravel()

In [621]:
reshaped_arr3[0] = 100
print(reshaped_arr3)
print(reshaped_arr1)

[100   2   3   4   5   6]
[[100   2   3]
 [  4   5   6]]


In [622]:
#flatten converts any numpy array into a 1D array and it creates a copy, therefore, modifications in a flatten array won't chage the original numpy array
reshaped_arr4 = reshaped_arr2.flatten()

In [623]:
reshaped_arr4[0] = 250
print(reshaped_arr4)
print(reshaped_arr2)

[250   2   3   4   5   6]
[[100   2]
 [  3   4]
 [  5   6]]


#Numpy array slicing

In [624]:
a = np.array([1, 2, 3, 4, 5])


In [625]:
a[ : 3] #ending indexed value is not included

array([1, 2, 3])

In [626]:
a[-1 : -4 : -1]

array([5, 4, 3])

In [627]:
a[-1 : -4] #default step value is 1, -1, 0, 1, 2, ... (it will never reach -4)

array([], dtype=int64)

In [628]:
a[ : : 2] #default starting index is 0

array([1, 3, 5])

In [629]:
a[:]

array([1, 2, 3, 4, 5])

In [630]:
a[2 :]

array([3, 4, 5])

In [631]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
    ])

In [632]:
matrix[: 2, [0, 2]].flatten() #slice + list

array([1, 3, 4, 6])

In [633]:
matrix[[1, 2], 2 : ] # list + slice

array([[6],
       [9]])

In [634]:
matrix[1 : , 1 : ]

array([[5, 6],
       [8, 9]])

In [635]:
matrix[[0, 1], [0, 2]] #row = 0 & column = 0, row = 1 & column = 2
                    #element-wise pairs
                    #np.array(arr[r1, c1], arr[r2, c2])

array([1, 6])

In [636]:
arr = np.array([1, 2, 3, 4, 5])
ids1 = [1, 2, 3] #indices
ids2 = [0, 3, 4] #indices
print(np.take(arr, ids1))
print(np.take(arr, ids2))

[2 3 4]
[1 4 5]


#Iterating in numpy array

In [637]:
arr = np.array([[1, 2, 3, 4, 5],
               [6, 7, 8, 9, 10]
               ])

In [638]:
for val in np.nditer(arr):
    print(val, end = " ")

1 2 3 4 5 6 7 8 9 10 

In [639]:
for idx, val in np.ndenumerate(arr):
    print(idx, val)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(0, 4) 5
(1, 0) 6
(1, 1) 7
(1, 2) 8
(1, 3) 9
(1, 4) 10


#View vs Copy

In [640]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [641]:
view_arr = arr.view()
view_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [642]:
view_arr[0][0] = 10
print(view_arr)
print(arr)

[[10  2  3]
 [ 4  5  6]]
[[10  2  3]
 [ 4  5  6]]


In [643]:
copy_arr = arr.copy()
copy_arr

array([[10,  2,  3],
       [ 4,  5,  6]])

In [644]:
copy_arr[0][0] = 1
print(copy_arr)
print(arr)

[[1 2 3]
 [4 5 6]]
[[10  2  3]
 [ 4  5  6]]


#Swapping

In [645]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [646]:
print(arr)
transposed_arr = arr.transpose()
print(transposed_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [647]:
matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
swapped_matrix = np.swapaxes(matrix, 0, 1) #swapping rows with colums
print(swapped_matrix)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [648]:
matrix[[0, 2]] = matrix[[2, 0]]
print(matrix)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


#Arithmetic operations on numpy array

In [649]:
arr1 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
arr2 = np.array(
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
)
print("Addition: ", arr1 + arr2)
print("\nSubtraction: ",arr2 - arr1)
print("\nMultiplication: ", arr1 * arr2)
print("\nInteger Division: ", arr2 // arr1)
print("\nDivision: ", arr2 / arr1)
print("\nModulo: ", arr2 % arr1)
print("\nExponent: ", arr1 ** 2)

Addition:  [[ 8 10 12]
 [14 16 18]]

Subtraction:  [[6 6 6]
 [6 6 6]]

Multiplication:  [[ 7 16 27]
 [40 55 72]]

Integer Division:  [[7 4 3]
 [2 2 2]]

Division:  [[7.  4.  3. ]
 [2.5 2.2 2. ]]

Modulo:  [[0 0 0]
 [2 1 0]]

Exponent:  [[ 1  4  9]
 [16 25 36]]


In [650]:
angles = np.array([0, np.pi / 3, np.pi / 4, np.pi / 6, np.pi / 2])
print(np.sin(angles))

[0.         0.8660254  0.70710678 0.5        1.        ]


In [651]:
exponent_vals = np.exp([1, 2, 3, 4, 5])
print(exponent_vals)

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


#Joining and splitting numpy arrays

In [652]:
arra = np.array([[1, 2, 3],
                [4, 5, 6]])
arrb = np.array([[7, 8, 9],
                [10, 11, 12]])

In [653]:
print(np.concatenate((arra, arrb)))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [654]:
print(np.vstack((arra, arrb)))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [655]:
print(np.hstack((arra, arrb)))

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [656]:
print(np.stack((arra, arrb), axis = 0)) #axis = 0, row-wise concatenation

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [657]:
print(np.stack((arra, arrb), axis = 1)) #axis = 1, column-wise concatenation

[[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]


In [658]:
print(np.split(arra, 2))

[array([[1, 2, 3]]), array([[4, 5, 6]])]


In [659]:
try:
    print(np.split(arrb, 3)) #splitting requires equal division
except Exception as e:
    print(e)

array split does not result in an equal division


In [660]:
print(np.vsplit(arra, 2))

[array([[1, 2, 3]]), array([[4, 5, 6]])]


In [661]:
print(np.hsplit(arrb, 3))

[array([[ 7],
       [10]]), array([[ 8],
       [11]]), array([[ 9],
       [12]])]


#Repeatation

In [662]:
#repeat - each element is repeated
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(np.repeat(arr, 2))

[1 1 2 2 3 3 4 4 5 5 6 6 7 7 8 8 9 9]


In [663]:
#tile - whole array is repeated
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(np.tile(arr, 2))

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]


#Aggregate functions in numpy array

In [664]:
arr = np.array([7, 4, 9, 1, 2, 8, 6, 3, 5, 10])
print(np.median(arr)) #if the array elements are unorganized, then it'll figure out the median after rearranging them
print(np.mean(arr))
print(np.median(arr))
print(np.min(arr))
print(np.sum(arr))
print(np.average(arr))
print(np.std(arr)) #standard deviation - how spread out data is
print(np.var(arr)) #variance - square of standard deviation
print(np.cumsum(arr)) #cumulative sum
print(np.cumprod(arr)) #cumulative product

5.5
5.5
5.5
1
55
5.5
2.8722813232690143
8.25
[ 7 11 20 21 23 31 37 40 45 55]
[      7      28     252     252     504    4032   24192   72576  362880
 3628800]


In [665]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(np.median(matrix))
print(np.mean(matrix))
print(np.average(matrix))
print(np.min(matrix))
print(np.max(matrix))
print(np.sum(matrix, axis = 0)) #row-wise sum
print(np.sum(matrix, axis = 1)) #column-wise sum
print(np.cumsum(matrix))
print(np.cumsum(matrix, axis = 0)) #row-wise cumulative sum
print(np.cumsum(matrix, axis = 1)) #column-wise cumulative sum
print(np.cumprod(matrix))
print(np.cumprod(matrix, axis = 0)) #row-wise cumulative product
print(np.cumprod(matrix, axis = 1)) #column-wise cumulative product
print(np.std(matrix))
print(np.std(matrix, axis = 0)) #row-wise standard deviation
print(np.std(matrix, axis = 1)) #column-wise standard deviation
print(np.var(matrix))
print(np.var(matrix, axis = 0)) #row-wise standard deviation
print(np.var(matrix, axis = 1)) #column-wise standard deviation

5.0
5.0
5.0
1
9
[12 15 18]
[ 6 15 24]
[ 1  3  6 10 15 21 28 36 45]
[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]
[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]
[     1      2      6     24    120    720   5040  40320 362880]
[[  1   2   3]
 [  4  10  18]
 [ 28  80 162]]
[[  1   2   6]
 [  4  20 120]
 [  7  56 504]]
2.581988897471611
[2.44948974 2.44948974 2.44948974]
[0.81649658 0.81649658 0.81649658]
6.666666666666667
[6. 6. 6.]
[0.66666667 0.66666667 0.66666667]


#Conditional based choices

In [666]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [667]:
print(np.where(matrix >= 5))
# cells = (1, 1), (1, 2), (2, 0), (2, 1), (2, 2)

(array([1, 1, 2, 2, 2]), array([1, 2, 0, 1, 2]))


In [668]:
print(np.where(matrix >= 5, 1, 0)) #if True, then 1, else False

[[0 0 0]
 [0 1 1]
 [1 1 1]]


In [669]:
print(np.argwhere(matrix >= 5))

[[1 1]
 [1 2]
 [2 0]
 [2 1]
 [2 2]]


In [670]:
mask = np.logical_and(matrix > 5, matrix <= 8) #6 and 7, both are greater than 5 and less than 8
print(mask)
matrix[mask]

[[False False False]
 [False False  True]
 [ True  True False]]


array([6, 7, 8])

In [671]:
mask = np.logical_or(matrix >= 5, matrix < 8) #every element is either grether than or equal to 5 or less than 8
print(mask)
matrix[mask]

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [672]:
mask = np.logical_not(matrix <= 5) #5, 6, 7, 8, 9 are greater than or equal to 5, therefore, we'll get True
                                  #1, 2, 3, 4, 5 are less than or equal to 5, therefore, we'll get False
print(mask)
matrix[mask]

[[False False False]
 [False False  True]
 [ True  True  True]]


array([6, 7, 8, 9])

In [673]:
mask = np.logical_xor(matrix > 3, matrix < 7) #True if exactly ONE condition is True and False if both are True OR both are False
print(mask)
matrix[mask]

[[ True  True  True]
 [False False False]
 [ True  True  True]]


array([1, 2, 3, 7, 8, 9])

In [674]:
print(np.take(matrix, [0, 2], axis = 0)) #fetch indiced based on row indices 0 and 2

[[1 2 3]
 [7 8 9]]


In [675]:
print(np.take(matrix, [0, 2], axis = 1)) #fetch elements based on column indices 0 and 2

[[1 3]
 [4 6]
 [7 9]]


In [676]:
print(np.take(matrix, [0, 3, 5])) #numpy will flatten the matrix (convert matrix into 1D array, then fetch the elements based on indices)

[1 4 6]


In [677]:
identity_matrix = np.array([
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1]
])
print(np.nonzero(identity_matrix))
#prints the positions (row, column) of non-zero elements in the identity_matrix

(array([0, 1, 2]), array([0, 1, 2]))


#Broadcasting (stretching the shape of smaller array so that it matches the bigger array)

In [678]:
arr_one = np.array([1, 2, 3])
np.shape(arr_one) #arr1 contains 3 elements, therefore, its shape is 3

(3,)

In [679]:
arr_two = np.array([[1], [2], [3]]) #one of the two must have a dimention of size 1
np.shape(arr_two) #arr2 contains 3 rows and 1 column

(3, 1)

In [680]:
print(arr_one + arr_two)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [681]:
array_1 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [682]:
array_2 = array_1 + 10
array_2

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [683]:
try:
    arr1 = np.array([
        [1, 2, 3],
        [4, 5, 6]
    ])
    arr2 = np.array([
        [1, 2],
        [3, 4],
        [5, 6]
    ])
    print(arr1 + arr2) #fails to broadcase, as none of the two has a dimention of size 1
except Exception as e:
    print(e)

operands could not be broadcast together with shapes (2,3) (3,2) 


#Vectorization

#Faster computation with numpy array compared to lists

In [684]:
import numpy as np #alias
import time

In [685]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] * 1000000
start_std = time.time()
for i in range(len(a)):
    a[i] = a[i] * 2
print("Time taken for list: ", time.time() - start_std)

Time taken for list:  1.1602709293365479


In [686]:
b = np.array(a)
start_np = time.time()
new_b = b * 2 #Vectorization allows element-wise operations without explicit loops
print("Time taken for numpy array: ", time.time() - start_np)

Time taken for numpy array:  0.04819464683532715


#Memory usage comparison in lists and numpy arrays

In [687]:
import sys
import numpy as np

In [688]:
c = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
d = np.array(c)
print("Memory usage of list: ", sys.getsizeof(c))
print("Memory usage of numpy array: ", d.nbytes)

Memory usage of list:  136
Memory usage of numpy array:  80


#Function call (When we wanna apply custom functions to every elements of an array)

In [689]:
def square(x):
    return x ** 2
arr = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])
vectorized_arr = np.vectorize(square)
print(vectorized_arr(arr))

[[ 1  4]
 [ 9 16]
 [25 36]]


#Dealing with missing values

In [690]:
arr_before = np.array([
    [1, np.nan, 3],
    [np.inf, 5, -np.inf],
    [7, 8, np.nan]
]) #nan = not a number, inf = infinity, np.inf = positive infinity, -np.inf = negative infinity

In [691]:
print(np.logical_or(np.isnan(arr_before), np.isinf(arr_before)))

[[False  True False]
 [ True False  True]
 [False False  True]]


In [692]:
arr_after = np.nan_to_num(arr_before)
arr_after #null vals are gonna be replaced by 0, positive and negative infinite vals are gonna be replaced by positive and negative large vals respectively

array([[ 1.00000000e+000,  0.00000000e+000,  3.00000000e+000],
       [ 1.79769313e+308,  5.00000000e+000, -1.79769313e+308],
       [ 7.00000000e+000,  8.00000000e+000,  0.00000000e+000]])